### ISSUE TITLE
Identified instances where extensions don't exist

### ISSUE THREAD

**Issue by exweeto** [IowaComputerGurus/DnnTelerikIdentifier#8]
Ran Telerik Identifier on a site and it came up with 4 dependencies, 1 of which I have an update for, 2 of which I don't know what they are, and 1 of which is a module that was installed, and deleted, years ago! Here is the list:

App_SubCode_EasyDNNnewsWidgets.dll
App_Web_view.ascx.c9cb6fcf.dll
App_Web_viewdnn71.ascx.c9cb6fcf.dll
DotNetNuke.RadEditorProvider.dll

I can sort the first one out. None of the other three seem to be related to anything currently installed on my site. Can you advise what I would need to do in a case like this? Should I just ignore these as, presumably, remnants of modules that have been deleted already, and therefore not of concern? Or is it likely that their presence is going to cause trouble if I remove Telerik from the site? If the latter, any tips on how I can find and remove the module remnants?

**Comment by mitchelsellers** [comment]
The App_Web ones are dynamically compiled, you could try to delete the files.  If they come back, the parent file is still there.  But otherwise they should be ok to remove.

The last one looks like you still have the RadEditorProvider installed.  I would ensure that the provider is removed, and all references to it in the Web.Config are removed, then you should be safe to remove the file.

**Comment by exweeto** [comment]
Excellent, thanks Mitchel. I'll give it a go!
